import type { WorkspaceTemplate } from "@workspace-pro/shared";
import { TEMPLATE_IDS } from "@workspace-pro/shared";

// ---------------------------------------------------------------------------
// Template Presets – pre-configured workspace layouts.
// Each template includes a set of PlacedItem defaults (x, y in grid units).
// ---------------------------------------------------------------------------

export const workspaceTemplates: WorkspaceTemplate[] = [
  {
    id: TEMPLATE_IDS.HOME_OFFICE,
    name: "Home Office",
    description: "Individual focus with domestic comfort.",
    imageUrl: "/placeholders/template-home-office.svg",
    defaultItems: [
      {
        instanceId: "tpl-ho-desk",
        id: "desk-standing",
        name: "Standing Desk",
        category: "desks",
        price: 120,
        imageUrl: "/placeholders/desk-standing.svg",
        dimensions: { width: 4, height: 2 },
        x: 200,
        y: 200,
        rotation: 0,
      },
      {
        instanceId: "tpl-ho-chair",
        id: "chair-ergo",
        name: "Ergonomic Chair",
        category: "chairs",
        price: 45,
        imageUrl: "/placeholders/chair-ergo.svg",
        dimensions: { width: 2, height: 2 },
        x: 280,
        y: 310,
        rotation: 0,
      },
      {
        instanceId: "tpl-ho-monitor",
        id: "misc-monitor",
        name: "Ultrawide Monitor",
        category: "misc",
        price: 80,
        imageUrl: "/placeholders/misc-monitor.svg",
        dimensions: { width: 3, height: 1 },
        x: 220,
        y: 170,
        rotation: 0,
      },
      {
        instanceId: "tpl-ho-plant",
        id: "misc-plant",
        name: "Indoor Plant",
        category: "misc",
        price: 20,
        imageUrl: "/placeholders/misc-plant.svg",
        dimensions: { width: 1, height: 1 },
        x: 380,
        y: 180,
        rotation: 0,
      },
    ],
  },
  {
    id: TEMPLATE_IDS.COLLABORATIVE,
    name: "Collaborative Studio",
    description: "Teams, modular tables, and breakout areas.",
    imageUrl: "/placeholders/template-collaborative.svg",
    defaultItems: [
      {
        instanceId: "tpl-cs-desk1",
        id: "desk-compact",
        name: "Compact Desk",
        category: "desks",
        price: 60,
        imageUrl: "/placeholders/desk-compact.svg",
        dimensions: { width: 3, height: 2 },
        x: 100,
        y: 200,
        rotation: 0,
      },
      {
        instanceId: "tpl-cs-desk2",
        id: "desk-compact",
        name: "Compact Desk",
        category: "desks",
        price: 60,
        imageUrl: "/placeholders/desk-compact.svg",
        dimensions: { width: 3, height: 2 },
        x: 350,
        y: 200,
        rotation: 0,
      },
      {
        instanceId: "tpl-cs-chair1",
        id: "chair-mesh",
        name: "Mesh Office Chair",
        category: "chairs",
        price: 35,
        imageUrl: "/placeholders/chair-mesh.svg",
        dimensions: { width: 2, height: 2 },
        x: 140,
        y: 320,
        rotation: 0,
      },
      {
        instanceId: "tpl-cs-chair2",
        id: "chair-mesh",
        name: "Mesh Office Chair",
        category: "chairs",
        price: 35,
        imageUrl: "/placeholders/chair-mesh.svg",
        dimensions: { width: 2, height: 2 },
        x: 390,
        y: 320,
        rotation: 0,
      },
      {
        instanceId: "tpl-cs-whiteboard",
        id: "misc-whiteboard",
        name: "Whiteboard",
        category: "misc",
        price: 35,
        imageUrl: "/placeholders/misc-whiteboard.svg",
        dimensions: { width: 4, height: 1 },
        x: 150,
        y: 80,
        rotation: 0,
      },
    ],
  },
  {
    id: TEMPLATE_IDS.EXECUTIVE,
    name: "Executive Suite",
    description: "Premium environment with refined aesthetics.",
    imageUrl: "/placeholders/template-executive.svg",
    defaultItems: [
      {
        instanceId: "tpl-es-desk",
        id: "desk-executive",
        name: "Executive Desk",
        category: "desks",
        price: 150,
        imageUrl: "/placeholders/desk-executive.svg",
        dimensions: { width: 5, height: 3 },
        x: 180,
        y: 180,
        rotation: 0,
      },
      {
        instanceId: "tpl-es-chair",
        id: "chair-lounge",
        name: "Lounge Chair",
        category: "chairs",
        price: 55,
        imageUrl: "/placeholders/chair-lounge.svg",
        dimensions: { width: 2, height: 3 },
        x: 280,
        y: 340,
        rotation: 0,
      },
      {
        instanceId: "tpl-es-shelf",
        id: "storage-shelf",
        name: "Bookshelf",
        category: "storage",
        price: 40,
        imageUrl: "/placeholders/storage-shelf.svg",
        dimensions: { width: 3, height: 1 },
        x: 100,
        y: 60,
        rotation: 0,
      },
      {
        instanceId: "tpl-es-plant",
        id: "misc-plant",
        name: "Indoor Plant",
        category: "misc",
        price: 20,
        imageUrl: "/placeholders/misc-plant.svg",
        dimensions: { width: 1, height: 1 },
        x: 450,
        y: 200,
        rotation: 0,
      },
      {
        instanceId: "tpl-es-lamp",
        id: "misc-lamp",
        name: "Desk Lamp",
        category: "misc",
        price: 25,
        imageUrl: "/placeholders/misc-lamp.svg",
        dimensions: { width: 1, height: 1 },
        x: 480,
        y: 150,
        rotation: 0,
      },
    ],
  },
];

// ---- Helpers ----

export function getTemplateById(id: string): WorkspaceTemplate | undefined {
  return workspaceTemplates.find((t) => t.id === id);
}
